; Nodo de monitoreo ambiental — ESP32-C3
; Board real conectada (verificada con esptool): ESP32-C3 (QFN32, single-core).
; Se usa la definicion generica esp32-c3-devkitm-1: el mapeo de pines lo da
; el chip, no la placa especifica del clon.

[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
build_flags =
	-D MQTT_MAX_PACKET_SIZE=1024
lib_deps =
	knolleary/PubSubClient@^2.8
	bblanchon/ArduinoJson@^7.0.4
	adafruit/DHT sensor library@^1.4.6
	adafruit/Adafruit Unified Sensor@^1.1.14
